/* global chrome */
import{fillWithAi}from'./ai.js';import{classifyPageContext,createDraft}from'./domain.js';import{listDrafts,loadSettings,markDraftForRetry,removeDraft,saveDraft,saveSettings}from'./storage.js';import{sendDraftToApp}from'./sync.js';
const form=document.querySelector('#capture-form'),feedback=document.querySelector('#feedback'),queue=document.querySelector('#queue'),aiButton=document.querySelector('#ai-fill'),settingsDialog=document.querySelector('#settings-dialog'),settingsForm=document.querySelector('#settings-form');let pageContext={url:'',title:'',domain:'',html:''};
const show=(message,kind='info')=>{feedback.textContent=message;feedback.dataset.kind=kind;};const field=name=>form.elements.namedItem(name);const esc=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
async function capture(){try{const[tab]=await chrome.tabs.query({active:true,currentWindow:true});const initial=classifyPageContext({url:tab?.url,title:tab?.title});if(!initial.ok||!tab?.id)return initial;await chrome.scripting.executeScript({target:{tabId:tab.id},files:['src/content.js']});const detail=await chrome.tabs.sendMessage(tab.id,{type:'CAPTURE_PAGE_CONTEXT'});const result=classifyPageContext(detail);if(result.ok)result.context.html=detail.html||'';return result;}catch{return{ok:false,message:'当前页面无采集权限，请手动填写企业和岗位信息。'};}}
async function render(){try{const items=await listDrafts();queue.innerHTML=items.length?items.map(d=>`<li><strong>${esc(d.company.name)}</strong><span>${esc(d.job.title)}</span><small>发送失败 · 已重试 ${d.attemptCount} 次</small><div><button data-action="retry" data-id="${d.id}" type="button">重新发送</button><button data-action="delete" data-id="${d.id}" type="button">删除</button></div></li>`).join(''):'<li class="empty">暂无发送失败的草稿</li>';}catch(error){show(error.message,'error');}}
function populate(values){for(const[name,value]of Object.entries(values))if(value&&field(name))field(name).value=value;}
document.querySelector('#open-settings').addEventListener('click',async()=>{const settings=await loadSettings();settingsForm.elements.provider.value=settings.provider;settingsForm.elements.apiKey.value=settings.apiKey;settingsForm.elements.model.value=settings.model;settingsDialog.showModal();});document.querySelector('#cancel-settings').addEventListener('click',()=>settingsDialog.close());settingsForm.addEventListener('submit',async event=>{event.preventDefault();await saveSettings(Object.fromEntries(new FormData(settingsForm)));settingsDialog.close();show('AI 设置已保存。','success');});
aiButton.addEventListener('click',async()=>{aiButton.disabled=true;show('DeepSeek 正在读取页面，请稍候…');try{populate(await fillWithAi({settings:await loadSettings(),pageContext}));show('AI 已填写表单，请检查后手动点击“添加到投递台”。','success');}catch(error){show(error.message||'AI 填写失败，请重试。','error');}finally{aiButton.disabled=false;}});
form.addEventListener('submit',async event=>{event.preventDefault();let draft;try{draft=createDraft({...Object.fromEntries(new FormData(form)),...pageContext});show('正在发送到投递台…');await sendDraftToApp(draft);await removeDraft(draft.id);show('已发送到投递台，请在管理页确认。','success');}catch(error){if(draft)await saveDraft(draft);show(`${error.message||'发送失败'} 草稿已保留，可稍后重新发送。`,'error');await render();}});
queue.addEventListener('click',async event=>{const button=event.target instanceof Element?event.target.closest('button[data-action]'):null;if(!button)return;try{if(button.dataset.action==='delete')await removeDraft(button.dataset.id);else{const draft=(await listDrafts()).find(item=>item.id===button.dataset.id);if(!draft)return;await markDraftForRetry(draft.id);await sendDraftToApp(draft);await removeDraft(draft.id);show('草稿已重新发送到投递台。','success');}await render();}catch(error){show(error.message||'重新发送失败。','error');await render();}});
const result=await capture();if(result.ok){pageContext=result.context;field('sourceUrl').value=pageContext.url;field('jobTitle').value=pageContext.title;show(result.warning||`已读取 ${pageContext.domain}`,result.warning?'warning':'success');}else show(result.message,'warning');await render();
