export const RESUME_DOCUMENT_VERSION=1;
export const PLATFORM_SCHEMA_VERSION=1;
const MAX_FIELDS=500,MAX_KEY=120,MAX_VALUE=20000,MAX_SELECTOR=1000;
const own=(value,key)=>Object.prototype.hasOwnProperty.call(value,key);
const record=value=>value!==null&&typeof value==='object'&&!Array.isArray(value);
function exact(value,keys,label){if(!record(value))throw new TypeError(`${label} must be an object`);const allowed=new Set(keys);for(const key of Object.keys(value))if(!allowed.has(key))throw new TypeError(`${label} contains unknown field ${key}`);for(const key of keys)if(!own(value,key))throw new TypeError(`${label} is missing ${key}`);}
function text(value,label,max,{empty=true}={}){if(typeof value!=='string')throw new TypeError(`${label} must be a string`);if(value.length>max)throw new TypeError(`${label} is too long`);if(!empty&&!value.trim())throw new TypeError(`${label} must not be empty`);return value;}
function timestamp(value,label){const result=text(value,label,40,{empty:false});if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/.test(result)||Number.isNaN(Date.parse(result)))throw new TypeError(`${label} must be an ISO UTC timestamp`);return result;}
function unique(items,key,label){const seen=new Set();for(const item of items){const value=item[key];if(seen.has(value))throw new TypeError(`${label} contains duplicate ${key} ${value}`);seen.add(value);}}
function safeKey(value,label){const key=text(value,label,MAX_KEY,{empty:false}).trim();if(!/^[A-Za-z][A-Za-z0-9_.-]*$/.test(key))throw new TypeError(`${label} must be a stable dotted key`);if(['__proto__','prototype','constructor'].includes(key))throw new TypeError(`${label} is unsafe`);return key;}

function parseResumeField(value,index){const label=`resume.fields[${index}]`;exact(value,['key','label','value'],label);return{key:safeKey(value.key,`${label}.key`),label:text(value.label,`${label}.label`,120,{empty:false}).trim(),value:text(value.value,`${label}.value`,MAX_VALUE)};}
export function parseResumeDocument(value){exact(value,['version','updatedAt','fields'],'resume');if(value.version!==RESUME_DOCUMENT_VERSION)throw new TypeError(`unsupported resume version ${String(value.version)}`);timestamp(value.updatedAt,'resume.updatedAt');if(!Array.isArray(value.fields)||value.fields.length>MAX_FIELDS)throw new TypeError(`resume.fields must contain at most ${MAX_FIELDS} items`);const fields=value.fields.map(parseResumeField);unique(fields,'key','resume.fields');return{version:RESUME_DOCUMENT_VERSION,updatedAt:value.updatedAt,fields};}
export function createResumeDocument(fields=[],updatedAt=new Date().toISOString()){return parseResumeDocument({version:RESUME_DOCUMENT_VERSION,updatedAt,fields});}
export function resumeValues(document){const parsed=parseResumeDocument(document),values=Object.create(null);for(const field of parsed.fields)values[field.key]=field.value;return values;}

const CONTROL_TYPES=new Set(['text','textarea','select','radio','checkbox','date','file','custom']);
function parseOption(value,index,label){exact(value,['value','label'],`${label}.options[${index}]`);return{value:text(value.value,`${label}.options[${index}].value`,500),label:text(value.label,`${label}.options[${index}].label`,500)};}
function parseMapping(value,index){const label=`schema.fields[${index}]`;exact(value,['key','label','selector','control','required','options'],label);const control=text(value.control,`${label}.control`,20,{empty:false});if(!CONTROL_TYPES.has(control))throw new TypeError(`${label}.control is unsupported`);if(typeof value.required!=='boolean')throw new TypeError(`${label}.required must be boolean`);if(!Array.isArray(value.options)||value.options.length>500)throw new TypeError(`${label}.options must be an array`);const options=value.options.map((option,n)=>parseOption(option,n,label));unique(options,'value',`${label}.options`);return{key:safeKey(value.key,`${label}.key`),label:text(value.label,`${label}.label`,120,{empty:false}).trim(),selector:text(value.selector,`${label}.selector`,MAX_SELECTOR,{empty:false}).trim(),control,required:value.required,options};}
export function parsePlatformSchema(value){exact(value,['version','platform','urlPatterns','capturedAt','fields'],'schema');if(value.version!==PLATFORM_SCHEMA_VERSION)throw new TypeError(`unsupported platform schema version ${String(value.version)}`);const platform=text(value.platform,'schema.platform',120,{empty:false}).trim();timestamp(value.capturedAt,'schema.capturedAt');if(!Array.isArray(value.urlPatterns)||!value.urlPatterns.length||value.urlPatterns.length>50)throw new TypeError('schema.urlPatterns must contain 1-50 items');const urlPatterns=value.urlPatterns.map((pattern,index)=>text(pattern,`schema.urlPatterns[${index}]`,1000,{empty:false}).trim());if(new Set(urlPatterns).size!==urlPatterns.length)throw new TypeError('schema.urlPatterns contains duplicates');if(!Array.isArray(value.fields)||value.fields.length>MAX_FIELDS)throw new TypeError(`schema.fields must contain at most ${MAX_FIELDS} items`);const fields=value.fields.map(parseMapping);unique(fields,'selector','schema.fields');return{version:PLATFORM_SCHEMA_VERSION,platform,urlPatterns,capturedAt:value.capturedAt,fields};}
export function createPlatformSchema(input){return parsePlatformSchema({version:PLATFORM_SCHEMA_VERSION,...input});}

function parseJson(source,label){if(typeof source!=='string')throw new TypeError(`${label} must be JSON text`);let value;try{value=JSON.parse(source);}catch{throw new TypeError(`${label} is not valid JSON`);}return value;}
export const exportResumeDocument=value=>`${JSON.stringify(parseResumeDocument(value),null,2)}\n`;
export const importResumeDocument=source=>parseResumeDocument(parseJson(source,'resume import'));
export const exportPlatformSchema=value=>`${JSON.stringify(parsePlatformSchema(value),null,2)}\n`;
export const importPlatformSchema=source=>parsePlatformSchema(parseJson(source,'schema import'));

export function buildFillPlan(document,schema){const values=resumeValues(document),parsedSchema=parsePlatformSchema(schema);return parsedSchema.fields.map(field=>({...field,value:own(values,field.key)?values[field.key]:'',missing:!own(values,field.key)||values[field.key]===''}));}
