export type Company = { id: string; name: string; shortName: string; ownership: string; industry: string; website: string; recruitmentUrl: string; description: string; applicationLimit: number | null; deadline: string; notes: string; createdAt: string; updatedAt: string };
export type Job = { id: string; companyId: string; title: string; batch: string; location: string; category: string; url: string; jd: string; status: string; appliedAt: string; deadline: string; progress: string; resumeName: string; notes: string; createdAt: string; updatedAt: string };
const DB_NAME = "job-application-tracker"; const DB_VERSION = 1;
const seeds: Array<[string,string,string,string]> = [
  ["国家电网有限公司","国家电网","能源电力","www.sgcc.com.cn"],["中国石油天然气集团","中石油","能源电力","www.cnpc.com.cn"],["中国石油化工集团","中石化","能源电力","www.sinopecgroup.com"],["中国海洋石油集团","中海油","能源电力","www.cnooc.com.cn"],["国家能源投资集团","国家能源","能源电力","www.chnenergy.com.cn"],
  ["中国移动通信集团","中国移动","通信","www.10086.cn"],["中国联合网络通信集团","中国联通","通信","www.chinaunicom.com.cn"],["中国电信集团","中国电信","通信","www.chinatelecom.com.cn"],
  ["中国工商银行","工行","金融","www.icbc.com.cn"],["中国建设银行","建行","金融","www.ccb.com"],["中国银行","中行","金融","www.boc.cn"],["中国农业银行","农行","金融","www.abchina.com.cn"],["中国人寿保险集团","中国人寿","金融","www.chinalife.com.cn"],["北京银行","北京银行","金融","www.bankofbeijing.com.cn"],
  ["中国建筑集团","中国建筑","建筑基建","www.cscec.com.cn"],["中国中铁","中国中铁","建筑基建","www.crec.cn"],["中国铁建","中国铁建","建筑基建","www.crcc.cn"],["北京城建集团","北京城建","建筑基建","www.bucg.com"],
  ["中国航天科技集团","航天科技","军工/航天/核工业","www.spacechina.com"],["中国航天科工集团","航天科工","军工/航天/核工业","www.casic.com.cn"],["中国核工业集团","中核集团","军工/航天/核工业","www.cnnc.com.cn"],["中国兵器工业集团","兵工集团","军工/航天/核工业","www.norincogroup.com.cn"],["中国兵器装备集团","兵装集团","军工/航天/核工业","www.csgc.com.cn"],["中国电子科技集团","中国电科","军工/航天/核工业","www.cetc.com.cn"],["中国航空发动机集团","中国航发","军工/航天/核工业","www.aecc.cn"],["中国电子信息产业集团","中国电子","军工/航天/核工业","www.cec.com.cn"],
  ["中粮集团","中粮","综合产业","www.cofco.com"],["华润集团","华润","综合产业","www.crc.com.hk"],["中国医药集团","国药集团","综合产业","www.sinopharm.com"],["中国保利集团","保利","综合产业","www.poly.com.cn"],["招商局集团","招商局","综合产业","www.cmhk.com"],
  ["首钢集团","首钢","北京市属重点国企","www.shougang.com.cn"],["北京汽车集团","北汽集团","北京市属重点国企","www.baicgroup.com.cn"],["中国交通建设集团","中交建","基建/重工","www.ccccltd.cn"],["中国船舶集团","中国船舶","基建/重工","www.cssc.net.cn"],["中国航空工业集团","航空工业","基建/重工","www.avic.com"],["中国中车集团","中国中车","基建/重工","www.crrcgc.cc"]
];
function openDb(): Promise<IDBDatabase> { return new Promise((resolve,reject) => { const req=indexedDB.open(DB_NAME,DB_VERSION); req.onupgradeneeded=()=>{ const db=req.result; if(!db.objectStoreNames.contains("companies")) db.createObjectStore("companies",{keyPath:"id"}); if(!db.objectStoreNames.contains("jobs")){ const s=db.createObjectStore("jobs",{keyPath:"id"}); s.createIndex("companyId","companyId"); }}; req.onsuccess=async()=>{ const db=req.result; const countReq=db.transaction("companies").objectStore("companies").count(); countReq.onsuccess=()=>{ if(countReq.result===0){ const tx=db.transaction("companies","readwrite"), now=new Date().toISOString(); seeds.forEach(([name,shortName,industry,website],i)=>tx.objectStore("companies").put({id:`seed-${i+1}`,name,shortName,industry,website,recruitmentUrl:"",description:`总部位于北京的${industry}领域重点企业。`,ownership:name.includes("北京")||name.includes("首钢")?"北京市属国企":"央企",applicationLimit:null,deadline:"",notes:"",createdAt:now,updatedAt:now})); tx.oncomplete=()=>resolve(db); } else resolve(db); }; }; req.onerror=()=>reject(req.error); }); }
async function all<T>(store:string):Promise<T[]>{ const db=await openDb(); return new Promise((res,rej)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)}); }
export async function listCompanies(){ return (await all<Company>("companies")).sort((a,b)=>a.name.localeCompare(b.name,"zh-CN")); }
export async function listJobs(){ return all<Job>("jobs"); }
async function put(store:string,value:Company|Job){const db=await openDb();return new Promise<void>((res,rej)=>{const tx=db.transaction(store,"readwrite");tx.objectStore(store).put(value);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)});}
export async function saveCompany(v:Omit<Company,"id"|"createdAt"|"updatedAt">&Partial<Pick<Company,"id"|"createdAt"|"updatedAt">>){const now=new Date().toISOString();return put("companies",{...v,id:v.id||crypto.randomUUID(),createdAt:v.createdAt||now,updatedAt:now});}
export async function saveJob(v:Omit<Job,"id"|"createdAt"|"updatedAt">&Partial<Pick<Job,"id"|"createdAt"|"updatedAt">>){const now=new Date().toISOString();return put("jobs",{...v,id:v.id||crypto.randomUUID(),createdAt:v.createdAt||now,updatedAt:now});}
async function remove(store:string,id:string){const db=await openDb();return new Promise<void>((res,rej)=>{const tx=db.transaction(store,"readwrite");tx.objectStore(store).delete(id);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)});}
export async function deleteJob(id:string){return remove("jobs",id)}
export async function deleteCompany(id:string){const js=await listJobs();const db=await openDb();return new Promise<void>((res,rej)=>{const tx=db.transaction(["companies","jobs"],"readwrite");tx.objectStore("companies").delete(id);js.filter(j=>j.companyId===id).forEach(j=>tx.objectStore("jobs").delete(j.id));tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)});}
export async function exportData(){return {version:1,exportedAt:new Date().toISOString(),companies:await listCompanies(),jobs:await listJobs()};}
export async function importData(data:unknown){if(!data||typeof data!=="object")throw new Error("bad data");const candidate=data as {companies?:unknown;jobs?:unknown};if(!Array.isArray(candidate.companies)||!Array.isArray(candidate.jobs))throw new Error("bad data");const companies=candidate.companies as Company[],jobs=candidate.jobs as Job[];const db=await openDb();return new Promise<void>((res,rej)=>{const tx=db.transaction(["companies","jobs"],"readwrite");tx.objectStore("companies").clear();tx.objectStore("jobs").clear();companies.forEach(x=>tx.objectStore("companies").put(x));jobs.forEach(x=>tx.objectStore("jobs").put(x));tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)});}
